pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '''

		echo "Hello World...Executing Build"

		'''
            }
        }
        stage('Test') {
            steps {
                sh '''

		echo "In Test stage"

		'''
            }
        }
        stage('Deliver') {
            steps {
                sh '''

		echo "In deliver stage"
		'''
            }
        }
    }
}
